---
- name: Reboot
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  
- name: Wait for SSH to be up
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_ec2_public_ipv4'] }}"
    port: 22
    delay: 15
    state: started
  delegate_to: 127.0.0.1
  become: no